#!/run/current-system/sw/bin/bash

winId=$(xdotool getactivewindow)

props=$(xprop -id "$winId")

pid=$(echo "$props" | grep PID | awk '{print $3}')

# notify-send "$pid"

scratch=$(grep -e "$pid" `fd '.scratchpad.pid' '/tmp'` | awk '{ res=0; gsub(":", " ", $res); print $res }')

if [ -n "$scratch" ]; then

    scrachpadFile=$(echo "$scratch" | awk '{ res=$1 ; gsub("\.pid", "", $res); print $res }')
    winId=$(wmctrl -lp | grep $pid | awk '{ print $1 }');
    i3 "[id=\"$winId\"] move scratchpad";
    rm $scrachpadFile
    
else

    dropdownInstance=$(echo "$props" | grep -e "WM_CLASS" | grep -e "dropdown" | awk '{ res=3; gsub("[\",]", "", $res); print $res}')

    if [ -n "$dropdownInstance" ]; then
	i3 "[instance=\"$dropdownInstance\"] scratchpad show; [instance=\"$dropdownInstance\"] move position center"
    fi

fi
