#!/run/current-system/sw/bin/bash

function helpMsg() {
    echo -e "Usage: spawn program class"
}

function windowToggle() {
    file="$2"
    if [ -e $file ]; then
	i3 "[id=\"$1\"] move scratchpad"
	rm $file
    else
	i3 "[id=\"$1\"] scratchpad show; [id=\"$1\"] move position center"
	touch $file
    fi
}

[ -z "$1" ] || [ -z "$2" ] && helpMsg && exit

[ ! -e $file ] && exit;

PIDfile="/tmp/$2.scratchpad.pid"

pid=$(cat $PIDfile)

winId=$(wmctrl -lp | grep $pid | awk '{print $1}')

scratchpadFile="/tmp/$2.scratchpad" 

if [ -n "$winId" ] && xwininfo -id "$winId";
then
    # notify-send "Window detected"
    windowToggle $winId $scratchpadFile
else
    $1 &
    PID=$!;
    # notify-send "Booting up window $PID $PIDfile"
    echo "$PID" > $PIDfile;
    touch $scratchpadFile;
fi
