#!/usr/bin/env sh

last_streams=""
last_streams_file="/tmp/last_streams.log"
hasHistory=[ -e "$last_streams_file" ]

if hasHistory; then
    while read -r line; do
	last_streams="$line\\n$last_streams"
    done < "$last_streams_file"
fi

choice=$(printf "$last_streams" | dmenu -i -p "Select twitch streamer:")
[ -z "$choice" ] && notify-send "Pick a streamer first" && exit
notify-send -t 3000 "Loading $choice stream..."

# Update log if the choice not already in there
if hasHistory && [-z $(cat $last_streams_file | grep $choice) ]; then
    echo "$choice\n" >> /tmp/last_streams.log
fi


regex='(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'
if [[ $choice =~ $regex ]]
then 
    url=$choice
else
    url="twitch.tv/$choice" 
fi

error=$(streamlink -p mpv "$url" 480p 2>&1)
[ -n "$error" ] && notify-send "$error"
