#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
        typeit=1
        shift
fi

clipboard=$(xsel -b | tr -d '\n')
password=$(echo $clipboard | dmenu "$@")

[[ -n $password ]] || exit

xdotool type --clearmodifiers "$password" 
