#!/usr/bin/env bash

function helpMsg() {
    echo "Usage: pass2kpass [path_to_file_or_directory] (without the [])";
}

function tokpass() {
    file=$1;
    username=$2;
    group=$3;
    if [ -n $(grep -e gpg $file) ]; then
	echo "converting to $file kpass";
	passw=$(gpg -dq $file)
	name="${file##*/}"
	filename=$(basename -- "$file")
	extension="${filename##*.}"
	name="${filename%.*}"
	echo -e "Username: $username\nPassword: $passw\nURL: https://google.com" | ph add --noninteractive "$group/$name"
    fi;
}

path=$1;
is_dir=$([ -d "$path" ] &&  echo true);
is_file=$([ -f "$path" ] && echo true);

if [ ! $is_dir ] && [ ! $is_file ]; then 
    helpMsg;
    exit 1;
fi;

set -e

if $is_dir; then

    for file in $(find $path -type f -regex '.*\.gpg'); do
	tokpass $file;
    done;

else
    
    tokpass $path;

fi;

