entryPoints:
  http:
    address: ":80"
    forwardedHeaders:
      insecure: true
  https:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    watch: true

log:
  level: "DEBUG"
