#!/run/current-system/sw/bin/bash


function helpMsg() {
    echo -e "Usage: ddspawn type name args\n\n\
type is one of: konsole, emacs\n\n\
Example: ddspawn konsole konsole1 -e htop"
}

function showWindow() {
    i3 "[instance=\"dropdown_$1\"] scratchpad show; [instance=\"dropdown_$1\"] move position center"
    i3 "[title=\"dropdown_$1\"] scratchpad show; [title=\"dropdown_$1\"] move position center"
}

# Toggle floating dropdown window in i3, or start if non-existing.
# $1 - the type of the program
# $2 - the name of the window
# All other args are passed to the program in $1
# Window names are in dropdown_* to allow easily setting i3 settings.

[ -z "$1" ] || [ -z "$2" ] && helpMsg && exit

if xwininfo -tree -root | grep "dropdown_$2";
then
    echo "Window detected."
    showWindow $2
else

    rest="${@:3}" # All arguments except the first 2
    cmd=""

    case $1 in
	term)
	    cmd="st -n dropdown_$2 $rest"
	    ;;
	emacs)
	    cmd="emacsdropdown $2 $rest"
	    ;;
	*)
	    helpMsg
	    exit
	    ;;
    esac

    echo "$cmd"

    echo "Window not detected... spawning."

    $cmd &
    sleep 0.2
    showWindow $2

fi
